Shell/sh implementation: Fix ShellCheck error.

diff --git a/shell/sh/hcasl b/shell/sh/hcasl
--- a/shell/sh/hcasl
+++ b/shell/sh/hcasl
@@ -1,15 +1,15 @@
 #!/bin/sh
 # -*- coding: utf-8-unix -*-
 # vim:fileencoding=utf-8:ff=unix
-# @(#) Command line tool for "head -c N && shift 1 byte" loop. Version 1.0.0.20151113
+# @(#) Command line tool for "head -c N && shift 1 byte" loop. Version 1.0.1.20220710
 
 set -u
 umask 0022
-IFS=`printf ' \t\n_'`; IFS=${IFS%_}
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
 PATH=/bin:/usr/bin
 export IFS LC_ALL=C LANG=C PATH
 
-readonly progname=`basename "$0"`
+readonly progname="${0##*/}"
 
 # usage <status>
 usage() {
@@ -20,12 +20,12 @@ usage() {
 		    -o FILE
 		      place output in file FILE
 	EOT
-    exit $1
+    exit "$1"
 }
 
 # version (nop)
 version() {
-    echo "$progname 1.0.0"
+    echo "$progname 1.0.1"
     exit 0
 }
 
@@ -50,21 +50,20 @@ opt=
 while getopts 'hn:o:v' opt; do
     case $opt in
     h)      usage 0 ;;
-    n)      bytes=`tobytes "$OPTARG"` ;;
+    n)      bytes=$(tobytes "$OPTARG") ;;
     o)      output=$OPTARG ;;
     v)      version ;;
     \?)     usage 1 1>&2 ;;
     esac
 done
-shift `expr $OPTIND - 1`
+shift $((OPTIND - 1))
 
 if [ -z "$bytes" ]; then
     usage 1 1>&2
 fi
 
-if [ -n "$output" -a "$output" != - ]; then
-    { exec >"$output"; } 2>/dev/null
-    [ $? -eq 0 ] || error "$output: cannot open"
+if [ -n "$output" ] && [ "$output" != - ]; then
+    { exec >"$output"; } 2>/dev/null || error "$output: cannot open"
 fi
 
 exec od -A n -t d1 -v ${@+"$@"} |
@@ -74,7 +73,7 @@ awk '
 BEGIN {
   tail = 0
 }
-tail < '`expr "$bytes" - 1`' {
+tail < '$((bytes - 1))' {
   buf[tail++] = $0
   next
 }
